# Generated by Django 5.2.11 on 2026-02-16 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Province',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Regioni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codice_istat', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuni', to='shared.provincia')),
            ],
            options={
                'verbose_name_plural': 'Comuni',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='regione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='shared.regione'),
        ),
    ]
