# Generated by Django 5.2.11 on 2026-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_comune_slug_provincia_slug_regione_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='sigla',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
