# Generated by Django 5.1.15 on 2026-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_provincia_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Mezzi',
                'ordering': ['sigla'],
            },
        ),
    ]
