# Generated by Django 5.1.15 on 2026-02-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_mezzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipologiaIntervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipologia Intervento',
                'verbose_name_plural': 'Tipologie Interventi',
            },
        ),
    ]
