# Generated by Django 5.1.15 on 2026-02-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_specializzazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etichette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Etichetta',
                'verbose_name_plural': 'Etichette',
            },
        ),
    ]
