# Generated by Django 5.1.15 on 2026-02-13 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('formato', models.CharField(choices=[('640', '640x480'), ('1280', '720p (HD)'), ('1920', '1080p (Full HD)')], default='1280', max_length=4)),
                ('posizione', models.CharField(choices=[('VERT', 'Verticale'), ('ORIZ', 'Orizzontale')], default='ORIZ', max_length=4)),
                ('codino', models.CharField(choices=[('SENZA', 'Senza'), ('CODIN', 'Codino')], default='CODIN', max_length=5)),
                ('logo', models.CharField(choices=[('SENZ', 'Senza'), ('LOGO', 'Logo')], default='LOGO', max_length=4)),
                ('video', models.FileField(upload_to='video/original/')),
                ('video_watermarks', models.FileField(blank=True, null=True, upload_to='video/watermarks/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Caricato'), ('PROCESSING', 'In Elaborazione'), ('SUCCESS', 'Completato'), ('ERROR', 'Errore')], default='UPLOADED', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
