# Generated by Django 5.1.15 on 2026-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
