# Generated by Django 5.1.15 on 2026-02-16 20:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0008_etichette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField(blank=True, help_text='Contenuto formattato da Drupal')),
                ('data', models.DateField()),
                ('posizione', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='storia/image/')),
                ('didascalia', models.CharField(blank=True, max_length=255)),
                ('prima_pagina', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='storia/video/')),
                ('comune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storie_comune', to='shared.comune')),
                ('etichette', models.ManyToManyField(blank=True, related_name='storie', to='shared.etichette')),
            ],
            options={
                'verbose_name': 'Storia',
                'verbose_name_plural': 'Storie',
                'ordering': ['-data'],
            },
        ),
    ]
