# Generated by Django 5.1.15 on 2026-02-12 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='originali/%Y/%m/')),
                ('watermarked_file', models.ImageField(blank=True, null=True, upload_to='pubblicati/%Y/%m/')),
                ('posizione', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
