# Generated by Django 5.2.11 on 2026-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0008_etichette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visti_in_TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField(blank=True, help_text='Contenuto formattato da Drupal')),
                ('data', models.DateField()),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='visti_in_tv/image/')),
                ('didascalia', models.CharField(blank=True, max_length=255)),
                ('prima_pagina', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='visti_in_tv/video/')),
                ('etichette', models.ManyToManyField(blank=True, related_name='visti_in_tv', to='shared.etichette')),
            ],
            options={
                'verbose_name': 'Visti in TV',
                'verbose_name_plural': 'Visti in TV',
                'ordering': ['-data'],
            },
        ),
    ]
