# Generated by Django 5.2.11 on 2026-02-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_etichette'),
        ('visti_in_tv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visti_in_TV',
            new_name='VistoInTv',
        ),
    ]
