# Generated by Django 5.2.11 on 2026-02-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visti_in_tv', '0002_rename_visti_in_tv_vistointv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistointv',
            old_name='titolo',
            new_name='title',
        ),
    ]
