# Generated by Django 5.2.11 on 2026-02-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visti_in_tv', '0003_rename_titolo_vistointv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistointv',
            name='immagine',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='visti_in_tv/image/'),
        ),
        migrations.AlterField(
            model_name='vistointv',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='visti_in_tv/video/'),
        ),
    ]
