# Generated by Django 5.2.11 on 2026-02-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visti_in_tv', '0004_alter_vistointv_immagine_alter_vistointv_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistointv',
            name='codice_cartella',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vistointv',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='visti_in_tv/image/'),
        ),
        migrations.AlterField(
            model_name='vistointv',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='visti_in_tv/video/'),
        ),
    ]
